springdoc:
  api-docs:
    enabled: true
    path: /swagger/configuration
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    default-models-expand-depth: -1
    persist-authorization: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
