spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 5000ms
      connect-timeout: 30000ms
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}