name: Deploy

on:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  image-build:
    name: Image Build and Push to NCP Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY }}/server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: image-build
    steps:
      - name: Execute
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ${{ secrets.NCP_SECRET_KEY }} | docker login --username ${{ secrets.NCP_ACCESS_KEY }} --password-stdin ${{ secrets.CONTAINER_REGISTRY }}
            
            if [ $(docker ps -q -f name=server) ]; then
              docker stop server
              docker rm server
            fi

            docker pull ${{ secrets.CONTAINER_REGISTRY }}/server:${{ github.sha }}
            docker run --name server --restart unless-stopped --env-file ${{ secrets.ENV_FILE }} --network bugi -p 8080:8080 -d ${{ secrets.CONTAINER_REGISTRY }}/server:${{ github.sha }}
            docker image prune -f
